# Generated by Django 5.2.1 on 2025-07-18 13:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'music_genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MusicPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='platform_icons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'music_platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.musicgenre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musicplatform')),
            ],
            options={
                'db_table': 'songs',
                'indexes': [models.Index(fields=['genre'], name='songs_genre_i_8d6106_idx'), models.Index(fields=['artist'], name='songs_artist_e25abe_idx'), models.Index(fields=['created_at'], name='songs_created_42d740_idx')],
                'unique_together': {('title', 'artist')},
            },
        ),
    ]
