# Generated by Django 5.2.1 on 2025-07-19 04:12

from django.db import migrations, models, connection


def remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists (for SQLite compatibility)"""
    db_alias = schema_editor.connection.alias
    with connection.cursor() as cursor:
        # Check if index exists in SQLite
        if connection.vendor == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='index' AND name='songs_genre_i_8d6106_idx'")
            if cursor.fetchone():
                cursor.execute("DROP INDEX songs_genre_i_8d6106_idx")


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - recreate index if needed"""
    pass  # Index will be recreated if genre field is added back


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RunPython(remove_index_if_exists, reverse_remove_index),
        migrations.RemoveField(
            model_name='song',
            name='release_year',
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MusicGenre',
        ),
    ]
