# Generated by Django 5.2.1 on 2025-07-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveIndex(
            model_name='song',
            name='songs_genre_i_8d6106_idx',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_year',
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MusicGenre',
        ),
    ]
