# Generated by Django 5.2.1 on 2025-07-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
