# Generated by Django 5.2.1 on 2025-07-19 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Match'), ('matched', 'Matched'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'song_exchanges',
            },
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='songs_genre_a4b7c8_idx'),
        ),
        migrations.AddField(
            model_name='songexchange',
            name='received_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_exchanges', to='music.song'),
        ),
        migrations.AddField(
            model_name='songexchange',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songexchange',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songexchange',
            name='sent_song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchanges', to='music.song'),
        ),
        migrations.AddIndex(
            model_name='songexchange',
            index=models.Index(fields=['status', 'created_at'], name='song_exchan_status_f594f2_idx'),
        ),
        migrations.AddIndex(
            model_name='songexchange',
            index=models.Index(fields=['sender', 'created_at'], name='song_exchan_sender__e00847_idx'),
        ),
        migrations.AddIndex(
            model_name='songexchange',
            index=models.Index(fields=['receiver', 'created_at'], name='song_exchan_receive_1c7825_idx'),
        ),
    ]
