# Generated by Django 5.2.1 on 2025-08-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_uploader'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
    ]
