# Generated by Django 5.2.1 on 2025-08-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_song_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fun_fact',
            field=models.TextField(blank=True),
        ),
    ]
