# Generated by Django 5.2.1 on 2025-12-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_fun_fact'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='songs_genre_i_8d6106_idx',
        ),
    ]
