# Generated by Django 5.2.1 on 2025-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_remove_song_songs_genre_i_8d6106_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='songexchange',
            name='match_type',
            field=models.CharField(blank=True, choices=[('random', 'Random Match'), ('genre', 'Genre Match')], max_length=20, null=True),
        ),
    ]
