services:
    db:
        image: postgres:16
        container_name: soundly_db
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            # Use password authentication instead of trust
            - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
        volumes:
            - soundly-db:/var/lib/postgresql/data
    server:
        container_name: soundly_server
        image: ghcr.io/mubarak117136/soundly:prod
        environment:
            - DJANGO_SETTINGS_MODULE=soundly.settings.production
        # Use startup script to ensure directories exist, then start gunicorn
        command: >
            sh -c "
            mkdir -p /app/server/logs /app/server/static /app/server/media /app/server/socket &&
            chmod -R 755 /app/server/logs /app/server/static /app/server/media /app/server/socket &&
            gunicorn -w 6 -b unix:/app/server/socket/SERVER.sock soundly.wsgi:application
            "
        volumes:
            - ./server/.env:/app/server/.env
            - ./server/static:/app/server/static
            - ./server/soundly/static:/app/server/soundly/static
            - ./server/media:/app/server/media
            - ./server/socket:/app/server/socket
        depends_on:
            - db
volumes:
  soundly-db:
