# Generated by Django 5.2.1 on 2025-12-05 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['activity', 'created_at'], name='activity_co_activit_e9e267_idx'), models.Index(fields=['user', '-created_at'], name='activity_co_user_id_050ca9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction_type', models.CharField(choices=[('🎵', 'Musical Note'), ('🎶', 'Musical Notes'), ('🎸', 'Guitar'), ('🎹', 'Piano'), ('🥁', 'Drum'), ('🎤', 'Microphone')], default='🎵', max_length=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_reactions',
                'indexes': [models.Index(fields=['activity', '-created_at'], name='activity_re_activit_6302c1_idx'), models.Index(fields=['user', '-created_at'], name='activity_re_user_id_9d49f3_idx')],
                'unique_together': {('user', 'activity', 'reaction_type')},
            },
        ),
    ]
