# Generated by Django 5.2.1 on 2025-07-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_user_city_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
