# Generated by Django 5.2.1 on 2025-07-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_device_token_user_receive_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('artist', 'Artist'), ('influencer', 'Influencer')], default='basic', max_length=20, verbose_name='User Type'),
        ),
    ]
