FROM python:3.13.5
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=soundly.settings.dev
WORKDIR /app/server/

# Create required directories with proper permissions
RUN mkdir -p /app/server/logs \
    /app/server/static \
    /app/server/media \
    /app/server/socket && \
    chmod -R 755 /app/server/logs \
    /app/server/static \
    /app/server/media \
    /app/server/socket

COPY ./server /app/server/
COPY ./server/requirements /app/server/
RUN pip install --upgrade pip
RUN pip install -r requirements/dev.txt
