FROM python:3.12-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=soundly.settings.production
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    netcat-openbsd \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/server/

COPY ./server /app/server/
RUN pip install --upgrade pip

RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements/prod.txt
