# Generated by Django 4.2.21 on 2025-05-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_8bedf2_idx',
            old_fields=('recipient', 'unread'),
        ),
    ]
